workflows:
  ios-release:
    name: iOS App Store Release
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    integrations:
      app_store_connect: Codemagic
    
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.huseyinasir.otomotiv
      flutter: stable
      xcode: latest
      cocoapods: default
      
    scripts:
      - name: Generate CSR and Private Key
        script: |
          openssl req -nodes -newkey rsa:2048 -keyout ios_distribution.key -out certificate.csr -subj "/emailAddress=asirhuseyin@hotmail.com/CN=Huseyin Asir/C=TR"
          
    artifacts:
      - certificate.csr
      - ios_distribution.key
      
    publishing:
      email:
        recipients:
          - asirhuseyin@hotmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
